import Link from "next/link";
import React from "react";
import hydimg from "public/images/hydimg.avif";
import Head from "next/head";
import { metaData } from "@/config/siteConfig";

const About = () => {
  return (
    <>
      <style jsx>
        {`
          .about {
            border: 1px solid white;
            width: 250px;
            height: 150px;
            text-align: center;
            margin: 10px auto;
            background-color: transparent;
            color: black;
          }
          // .img {
          //   border: 1px solid transparent;
          //   width: 250px;
          //   height: 150px;
          //   margin: 10px auto;
          // }
        `}
      </style>
      <Head>
        <title>{metaData.about.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="about">
        <h3>Worked On</h3>
        <br />
        <Link href={`fetchFolder/what-is-weatherApp`}>
          <h5>Weather App</h5>
        </Link>
        <br />
        <Link href={`fetchFolder/what-is-To-Do-List`}>
          <h5>To-Do App</h5>
        </Link>
        <br />
        <Link href={`fetchFolder/what-is-calculator`}>
          <h5>Calculator App</h5>
        </Link>
        <br />
        <Link href={`fetchFolder/getting-html-content-from-server-side`}>
          <h5>Server Side</h5>
        </Link>
      </div>
      {/* <div className="img">
        <img src={hydimg.src} alt="hyderabad" width={250} height={150} />
      </div> */}
    </>
  );
};

export default About;
