import { metaData } from "@/config/siteConfig";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "@/styles/contact.module.css";
import axios from "axios";

const Contact = () => {
  const [username, setUserName] = useState("");
  const [email, setEmail] = useState("");
  const [number, setNumber] = useState("");
  const [password, setPassword] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    const body = {
      username,
      email,
      number,
      password,
    };
    if ((body.username && body.email && body.number && body.password) !== "") {
      const myFunction = async () => {
        let data = await axios.post(
          "http://localhost:3000/api/postRequest",
          body
        );
        if (password.length < 8) {
          alert(
            "Password is too short. It should be at least 8 characters long."
          );
        } else if (!/\d/.test(password)) {
          alert("Password should contain at least one number (0-9).");
        } else if (!/[A-Z]/.test(password)) {
          alert("Password should contain at least one uppercase letter.");
        } else if (!/[a-z]/.test(password)) {
          alert("Password should contain at least one lowercase letter.");
        } else {
          if (number.length !== 10) {
            alert("Please enter the valid contact!");
          } else {
            if (data.status === 200) {
              alert("Form Submitted succesfully!");
              console.log(body, 555);
              clearFormFields();
            }
          }
        }
      };
      myFunction();
      const clearFormFields = () => {
        setUserName("");
        setEmail("");
        setNumber("");
        setPassword("");
      };
    }
  };

  return (
    <>
      <Head>
        <title>{metaData.contact.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <form onSubmit={handleSubmit}>
          <div className={styles.lable}>UserName:</div>
          <input
            className={styles.input}
            required
            type="text"
            name="username"
            value={username}
            onChange={(e) => setUserName(e.target.value)}
          />
          <br />
          <div className={styles.lable}>E-Mail:</div>
          <input
            className={styles.input}
            required
            type="email"
            name="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
          <br />

          <div className={styles.lable}>Password:</div>
          <input
            className={styles.input}
            required
            type="password"
            name="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
          <br />
          <div className={styles.lable}>Contact:</div>
          <input
            className={styles.input}
            required
            pattern="[0-9]{10}"
            type="number"
            name="number"
            value={number}
            onChange={(e) => setNumber(e.target.value)}
          />
          <div className={styles.button}>
            <button type="submit">Submit</button>
          </div>
        </form>
      </div>
    </>
  );
};

export default Contact;
